### ISSUE TITLE
Message endpoint

### ISSUE THREAD

**Issue by gregmillz** [DATA-DOG/golang-websocket-hub#2]
Hi, thanks for making the package! I'm curious, why do you use the /message endpoint to send messages instead of message on the client-side using the connected websocket? Wouldn't we want to move away from REST? Or is the idea to give more control for auth?

**Comment by l3pp4rd** [comment]
Hi, do not remember it now, done this very long time ago. take whatever is useful and adapt it to your own use case

**Comment by gregmillz** [comment]
No problem, thanks for the quick response.
